# Generated by Django 4.0.6 on 2022-08-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(default=None, max_length=124)),
                ('race', models.CharField(default=None, max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.BooleanField()),
                ('camera', models.BooleanField()),
                ('is_private', models.BooleanField()),
                ('notifications', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=50)),
                ('firstname', models.CharField(default=None, max_length=50)),
                ('lastname', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default=None, max_length=16)),
                ('gender', models.CharField(default=None, max_length=124)),
                ('description', models.CharField(default=None, max_length=124)),
            ],
        ),
    ]
