# Generated by Django 4.0.6 on 2022-07-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('category', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
